# Generated by Django 5.1.5 on 2025-01-24 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='favorites',
            new_name='favorite',
        ),
    ]
