# Generated by Django 5.1.5 on 2025-01-29 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 29, 19, 50, 21, 305753, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
