# Generated by Django 5.1.5 on 2025-01-30 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 30, 19, 2, 38, 902592, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
