# Generated by Django 5.1.5 on 2025-02-07 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_article_category_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 12, 6, 9, 223672, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='news', to='news.category'),
        ),
    ]
