# Generated by Django 5.1.5 on 2025-02-07 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_article_category_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 12, 25, 13, 66663, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
