# Generated by Django 5.1.5 on 2025-02-07 15:59

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='article', to='news.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 15, 59, 6, 256657, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='favorites',
        ),
        migrations.AddField(
            model_name='article',
            name='favorites',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
