# Generated by Django 5.1.5 on 2025-02-07 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_author_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 16, 29, 35, 497649, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
