# Generated by Django 5.1.5 on 2025-02-07 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 17, 50, 29, 836291, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
