# Generated by Django 5.1.5 on 2025-02-07 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 7, 17, 55, 15, 251082, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
